/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.Armamento;
import aplicacion.Equipo;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alumnogreibd
 */
public class VArmamento extends javax.swing.JDialog {
    
    aplicacion.FachadaAplicacion fa;
    int modoEquipo = 0;
    boolean aModoNuevo = false;
    boolean eModoNuevo = false;
    SimpleDateFormat formato;
    int idGrupo;

    /**
     * Creates new form VUsuarios
     */
    public VArmamento(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, int idGrupo) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        formato = new SimpleDateFormat("yyyy-MM-dd");
        fa.equipamientoSetGrupo(idGrupo);
        this.idGrupo = idGrupo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        armamentoTabbedPane = new javax.swing.JTabbedPane();
        armamentoPane = new javax.swing.JPanel();
        aSerieBuscarLabel = new javax.swing.JLabel();
        aSerieBuscarText = new javax.swing.JTextField();
        aModeloBuscarLabel = new javax.swing.JLabel();
        aModeloBuscarText = new javax.swing.JTextField();
        aTipoBuscarLabel = new javax.swing.JLabel();
        aTipoBuscarText = new javax.swing.JTextField();
        aBuscarButton = new javax.swing.JButton();
        aSerieIntLabel = new javax.swing.JLabel();
        aSerieIntText = new javax.swing.JTextField();
        aModeloIntLabel = new javax.swing.JLabel();
        aModeloIntText = new javax.swing.JTextField();
        aTipoIntLabel = new javax.swing.JLabel();
        aTipoIntText = new javax.swing.JTextField();
        aEstadoIntLabel = new javax.swing.JLabel();
        aEstadoIntText = new javax.swing.JTextField();
        aUbicacionIntLabel = new javax.swing.JLabel();
        aUbicacionIntText = new javax.swing.JTextField();
        aFechaIntLabel = new javax.swing.JLabel();
        aFechaIntText = new javax.swing.JTextField();
        aBorrarButton = new javax.swing.JButton();
        aGuardarButton = new javax.swing.JButton();
        aNuevoButton = new javax.swing.JButton();
        aSalirButton = new javax.swing.JButton();
        aTuplasPane = new javax.swing.JScrollPane();
        armamentoTable = new javax.swing.JTable();
        aNuevoAvisoLabel = new javax.swing.JLabel();
        equipoPane = new javax.swing.JPanel();
        eIdBuscarLabel = new javax.swing.JLabel();
        eIdBuscarText = new javax.swing.JTextField();
        eNombreBuscarLabel = new javax.swing.JLabel();
        eNombreBuscarText = new javax.swing.JTextField();
        eBuscarButton = new javax.swing.JButton();
        eModoComboBox = new javax.swing.JComboBox<>();
        eTuplasPane = new javax.swing.JScrollPane();
        equipoTable = new javax.swing.JTable();
        eNombreIntLabel = new javax.swing.JLabel();
        eNombreIntText = new javax.swing.JTextField();
        eTipoIntLabel = new javax.swing.JLabel();
        eTipoIntText = new javax.swing.JTextField();
        eFechaIntText = new javax.swing.JTextField();
        eFechaIntLabel = new javax.swing.JLabel();
        eModoIntLabel = new javax.swing.JLabel();
        eModoIntText = new javax.swing.JTextField();
        eBorrarButton = new javax.swing.JButton();
        eGuardarButton = new javax.swing.JButton();
        eNuevoButton = new javax.swing.JButton();
        eSalirButton = new javax.swing.JButton();
        eNuevoAvisoLabel = new javax.swing.JLabel();
        eIdIntText = new javax.swing.JTextField();
        eIdIntLabel = new javax.swing.JLabel();
        eCompanhiaIntLabel = new javax.swing.JLabel();
        eCompanhiaIntText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        resumenPane = new javax.swing.JScrollPane();
        resumenTable = new javax.swing.JTable();
        actualizarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Equipamiento");

        armamentoTabbedPane.setName("Armamento"); // NOI18N

        aSerieBuscarLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        aSerieBuscarLabel.setText("Nº de Serie:");

        aModeloBuscarLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        aModeloBuscarLabel.setText("Modelo:");

        aTipoBuscarLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        aTipoBuscarLabel.setText("Tipo:");

        aBuscarButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aBuscarButton.setText("Buscar");
        aBuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBuscarButtonActionPerformed(evt);
            }
        });

        aSerieIntLabel.setText("Nº de Serie:");

        aModeloIntLabel.setText("Modelo:");

        aTipoIntLabel.setText("Tipo:");

        aEstadoIntLabel.setText("Estado:");

        aUbicacionIntLabel.setText("Ubicacion:");

        aUbicacionIntText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aUbicacionIntTextActionPerformed(evt);
            }
        });

        aFechaIntLabel.setText("F. de Adquisicion");

        aFechaIntText.setText("2000-01-30");
        aFechaIntText.setToolTipText("Formato: aaaa-mm-dd");

        aBorrarButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aBorrarButton.setText("Borrar");
        aBorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBorrarButtonActionPerformed(evt);
            }
        });

        aGuardarButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aGuardarButton.setText("Guardar");
        aGuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aGuardarButtonActionPerformed(evt);
            }
        });

        aNuevoButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aNuevoButton.setText("Nuevo");
        aNuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aNuevoButtonActionPerformed(evt);
            }
        });

        aSalirButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aSalirButton.setText("Salir");
        aSalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSalirButtonActionPerformed(evt);
            }
        });

        armamentoTable.setModel(new ModeloTablaArmamento());
        armamentoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                armamentoTableMouseClicked(evt);
            }
        });
        aTuplasPane.setViewportView(armamentoTable);

        javax.swing.GroupLayout armamentoPaneLayout = new javax.swing.GroupLayout(armamentoPane);
        armamentoPane.setLayout(armamentoPaneLayout);
        armamentoPaneLayout.setHorizontalGroup(
            armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armamentoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(armamentoPaneLayout.createSequentialGroup()
                        .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(armamentoPaneLayout.createSequentialGroup()
                                .addComponent(aSerieBuscarLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aSerieBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aModeloBuscarLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aModeloBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aTipoBuscarLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aTipoBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aBuscarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(aTuplasPane)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, armamentoPaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aSerieIntLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aEstadoIntLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(aSerieIntText)
                                    .addComponent(aEstadoIntText, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(armamentoPaneLayout.createSequentialGroup()
                                        .addComponent(aUbicacionIntLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aUbicacionIntText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(armamentoPaneLayout.createSequentialGroup()
                                        .addComponent(aModeloIntLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aModeloIntText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aFechaIntLabel)
                                    .addComponent(aTipoIntLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aFechaIntText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aTipoIntText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, armamentoPaneLayout.createSequentialGroup()
                                .addComponent(aSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aNuevoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aGuardarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aBorrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(armamentoPaneLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(aNuevoAvisoLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        armamentoPaneLayout.setVerticalGroup(
            armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armamentoPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aSerieBuscarLabel)
                    .addComponent(aSerieBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aModeloBuscarLabel)
                    .addComponent(aModeloBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aTipoBuscarLabel)
                    .addComponent(aTipoBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aBuscarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aTuplasPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aNuevoAvisoLabel)
                .addGap(29, 29, 29)
                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aSerieIntLabel)
                    .addComponent(aSerieIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aModeloIntLabel)
                    .addComponent(aModeloIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aTipoIntLabel)
                    .addComponent(aTipoIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aEstadoIntLabel)
                    .addComponent(aEstadoIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aUbicacionIntLabel)
                    .addComponent(aUbicacionIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aFechaIntLabel)
                    .addComponent(aFechaIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(armamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aSalirButton)
                    .addComponent(aNuevoButton)
                    .addComponent(aGuardarButton)
                    .addComponent(aBorrarButton))
                .addContainerGap())
        );

        armamentoTabbedPane.addTab("Armamento", armamentoPane);

        eIdBuscarLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        eIdBuscarLabel.setText("ID:");

        eNombreBuscarLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        eNombreBuscarLabel.setText("Nombre:");

        eBuscarButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eBuscarButton.setText("Buscar");
        eBuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBuscarButtonActionPerformed(evt);
            }
        });

        eModoComboBox.setMaximumRowCount(3);
        eModoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comunicacion", "Medico", "Proteccion" }));
        eModoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eModoComboBoxActionPerformed(evt);
            }
        });

        equipoTable.setModel(new ModeloTablaEquipo());
        equipoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipoTableMouseClicked(evt);
            }
        });
        eTuplasPane.setViewportView(equipoTable);

        eNombreIntLabel.setText("Nombre:");

        eTipoIntLabel.setText("Tipo:");

        eFechaIntText.setText("2000-01-30");
        eFechaIntText.setToolTipText("Formato: aaaa-mm-dd");

        eFechaIntLabel.setText("F. de Adquisicion:");

        eModoIntLabel.setText("Alcance:");

        eBorrarButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eBorrarButton.setText("Borrar");
        eBorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBorrarButtonActionPerformed(evt);
            }
        });

        eGuardarButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eGuardarButton.setText("Guardar");
        eGuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eGuardarButtonActionPerformed(evt);
            }
        });

        eNuevoButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eNuevoButton.setText("Nuevo");
        eNuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNuevoButtonActionPerformed(evt);
            }
        });

        eSalirButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eSalirButton.setText("Salir");
        eSalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSalirButtonActionPerformed(evt);
            }
        });

        eNuevoAvisoLabel.setToolTipText("");

        eIdIntLabel.setText("ID:");

        eCompanhiaIntLabel.setText("Compañia:");

        javax.swing.GroupLayout equipoPaneLayout = new javax.swing.GroupLayout(equipoPane);
        equipoPane.setLayout(equipoPaneLayout);
        equipoPaneLayout.setHorizontalGroup(
            equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipoPaneLayout.createSequentialGroup()
                        .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(equipoPaneLayout.createSequentialGroup()
                                .addComponent(eSalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eNuevoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eGuardarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eBorrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eTuplasPane)
                            .addGroup(equipoPaneLayout.createSequentialGroup()
                                .addComponent(eIdBuscarLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eIdBuscarText, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eNombreBuscarLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eNombreBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eModoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eBuscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(equipoPaneLayout.createSequentialGroup()
                                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eIdIntLabel)
                                    .addComponent(eNombreIntLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(eIdIntText)
                                    .addComponent(eNombreIntText, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eModoIntLabel)
                                    .addComponent(eTipoIntLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eModoIntText, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(eTipoIntText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(equipoPaneLayout.createSequentialGroup()
                                        .addComponent(eCompanhiaIntLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eCompanhiaIntText))
                                    .addGroup(equipoPaneLayout.createSequentialGroup()
                                        .addComponent(eFechaIntLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eFechaIntText, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(equipoPaneLayout.createSequentialGroup()
                        .addComponent(eNuevoAvisoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        equipoPaneLayout.setVerticalGroup(
            equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipoPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eIdBuscarLabel)
                    .addComponent(eIdBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNombreBuscarLabel)
                    .addComponent(eNombreBuscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eBuscarButton)
                    .addComponent(eModoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(eTuplasPane, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eNuevoAvisoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eCompanhiaIntLabel)
                        .addComponent(eCompanhiaIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eNombreIntLabel)
                        .addComponent(eNombreIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eTipoIntLabel)
                        .addComponent(eTipoIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eIdIntLabel)
                        .addComponent(eIdIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eFechaIntLabel)
                        .addComponent(eFechaIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eModoIntLabel)
                        .addComponent(eModoIntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eBorrarButton)
                        .addComponent(eGuardarButton)
                        .addComponent(eNuevoButton))
                    .addComponent(eSalirButton))
                .addGap(44, 44, 44))
        );

        armamentoTabbedPane.addTab("Equipo", equipoPane);

        resumenTable.setModel(new ModeloTablaArmamentoResumen());
        resumenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resumenTableMouseClicked(evt);
            }
        });
        resumenPane.setViewportView(resumenTable);

        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(actualizarButton)
                    .addComponent(resumenPane, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(actualizarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resumenPane, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        armamentoTabbedPane.addTab("Resumen", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(armamentoTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(armamentoTabbedPane)
        );

        armamentoTabbedPane.getAccessibleContext().setAccessibleName("Armamento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eSalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSalirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_eSalirButtonActionPerformed

    private void eNuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNuevoButtonActionPerformed

        if(!eModoNuevo){
            eNuevoAvisoLabel.setText("Introduciendo nuevo equipo");
            eModoNuevo = true;

            eNombreIntText.setText("");
            eTipoIntText.setText("");
            eFechaIntText.setText("");
            eModoIntText.setText("");
            eCompanhiaIntText.setText("");
            eIdIntText.setText("");
            eGuardarButton.setEnabled(true);
        }else{
            eNuevoAvisoLabel.setText(" ");
            eModoNuevo = false;
        }
    }//GEN-LAST:event_eNuevoButtonActionPerformed

    private void eGuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eGuardarButtonActionPerformed

        ModeloTablaEquipo m;
        m = (ModeloTablaEquipo)equipoTable.getModel();

        int id = Integer.parseInt(eIdIntText.getText());
        String companhia = eCompanhiaIntText.getText();
        String nombre = eNombreIntText.getText();
        String tipo = eTipoIntText.getText();
        Date fechaAdquisicion;
        String propiedad = eModoIntText.getText();

        try{
            fechaAdquisicion = formato.parse(eFechaIntText.getText());
        }catch(ParseException e){
            fechaAdquisicion = new GregorianCalendar(2000, Calendar.JANUARY, 1).getTime();
        }

        Equipo nuevoEquipo = new Equipo(id, companhia, nombre,tipo,fechaAdquisicion,idGrupo,propiedad);

        if(eModoNuevo){
            fa.insertarEquipo(nuevoEquipo, modoEquipo);

            eNombreIntText.setText("");
            eTipoIntText.setText("");
            eFechaIntText.setText("");
            eModoIntText.setText("");
            eCompanhiaIntText.setText("");
            eIdIntText.setText("");

            eNuevoAvisoLabel.setText(" ");
            eModoNuevo = false;

        }else{
            Equipo selectedEquipo = m.obtenerEquipo(equipoTable.getSelectedRow());
            fa.actualizarEquipo(selectedEquipo.getId(), nuevoEquipo, modoEquipo);
        }

        m.setFilas(fa.obtenerEquipo(eIdBuscarText.getText(), eNombreBuscarText.getText(), modoEquipo));

    }//GEN-LAST:event_eGuardarButtonActionPerformed

    private void eBorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBorrarButtonActionPerformed

        ModeloTablaEquipo m;
        m = (ModeloTablaEquipo)equipoTable.getModel();

        Equipo selectedEquipo = m.obtenerEquipo(equipoTable.getSelectedRow());

        fa.borrarEquipo(selectedEquipo.getId(), modoEquipo);

        m.setFilas(fa.obtenerEquipo(eIdBuscarText.getText(), eNombreBuscarText.getText(), modoEquipo));
    }//GEN-LAST:event_eBorrarButtonActionPerformed

    private void equipoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipoTableMouseClicked

        ModeloTablaEquipo m = (ModeloTablaEquipo) equipoTable.getModel();
        if(equipoTable.getSelectedRow() >= 0){

            eNombreIntText.setText(String.valueOf(m.obtenerEquipo(equipoTable.getSelectedRow()).getNombre()));
            eTipoIntText.setText(m.obtenerEquipo(equipoTable.getSelectedRow()).getTipo());
            eCompanhiaIntText.setText(m.obtenerEquipo(equipoTable.getSelectedRow()).getCompanhia());
            eIdIntText.setText(String.valueOf(m.obtenerEquipo(equipoTable.getSelectedRow()).getId()));
            eModoIntText.setText(m.obtenerEquipo(equipoTable.getSelectedRow()).getPropiedad());
            eFechaIntText.setText(String.valueOf(m.obtenerEquipo(equipoTable.getSelectedRow()).getFechaAdquisicion()));

            eGuardarButton.setEnabled(true);
            eBorrarButton.setEnabled(true);
        }
    }//GEN-LAST:event_equipoTableMouseClicked

    private void eModoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eModoComboBoxActionPerformed

        ModeloTablaEquipo m;
        m = (ModeloTablaEquipo)equipoTable.getModel();
        modoEquipo = eModoComboBox.getSelectedIndex();

        m.setModo(modoEquipo);
        m.fireTableStructureChanged();
        buscarEquipo();
        switch (modoEquipo) {
            case 0:
            //Comunicacion
            eModoIntLabel.setText("Alcance");
            break;
            case 1:
            //Medico
            eModoIntLabel.setText("Categoria");
            break;
            case 2 :
            //Proteccion
            eModoIntLabel.setText("Material");
            break;
            default:
        }
    }//GEN-LAST:event_eModoComboBoxActionPerformed

    private void eBuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBuscarButtonActionPerformed
        buscarEquipo();
    }//GEN-LAST:event_eBuscarButtonActionPerformed

    private void armamentoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_armamentoTableMouseClicked

        ModeloTablaArmamento m = (ModeloTablaArmamento) armamentoTable.getModel();
        if(armamentoTable.getSelectedRow() >= 0){

            aSerieIntText.setText(String.valueOf(m.obtenerArma(armamentoTable.getSelectedRow()).getNumSerie()));
            aModeloIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getModelo());
            aTipoIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getTipo());
            aEstadoIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getEstado());
            aUbicacionIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getUbicacion());
            aFechaIntText.setText(String.valueOf(m.obtenerArma(armamentoTable.getSelectedRow()).getFechaAdquisicion()));

            aGuardarButton.setEnabled(true);
            aBorrarButton.setEnabled(true);
        }
    }//GEN-LAST:event_armamentoTableMouseClicked

    private void aSalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSalirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_aSalirButtonActionPerformed

    private void aNuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aNuevoButtonActionPerformed

        if(!aModoNuevo){
            aNuevoAvisoLabel.setText("Introduciendo nuevo armamento");
            aModoNuevo = true;

            aSerieIntText.setText("");
            aModeloIntText.setText("");
            aTipoIntText.setText("");
            aEstadoIntText.setText("");
            aUbicacionIntText.setText("");
            aFechaIntText.setText("");

            aGuardarButton.setEnabled(true);

        }else{
            aNuevoAvisoLabel.setText(" ");
            aModoNuevo = false;
        }
    }//GEN-LAST:event_aNuevoButtonActionPerformed

    private void aGuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aGuardarButtonActionPerformed

        ModeloTablaArmamento m;
        m = (ModeloTablaArmamento)armamentoTable.getModel();

        int numSerie = Integer.parseInt(aSerieIntText.getText());
        String tipo = aTipoIntText.getText();
        String modelo = aModeloIntText.getText();
        String estado = aEstadoIntText.getText();
        String ubicacion = aUbicacionIntText.getText();
        Date fechaAdquisicion;

        try{
            fechaAdquisicion = formato.parse(aFechaIntText.getText());
        }catch(ParseException e){
            fechaAdquisicion = new GregorianCalendar(2000, Calendar.JANUARY, 1).getTime();
        }

        Armamento nuevoArma = new Armamento(numSerie,tipo,modelo,estado,ubicacion,fechaAdquisicion,idGrupo);

        if(aModoNuevo){
            fa.insertarArmamento(nuevoArma);

            aSerieIntText.setText("");
            aModeloIntText.setText("");
            aTipoIntText.setText("");
            aEstadoIntText.setText("");
            aUbicacionIntText.setText("");
            aFechaIntText.setText("");

            aNuevoAvisoLabel.setText(" ");
            aModoNuevo = false;

        }else{

            Armamento selectedArma = m.obtenerArma(armamentoTable.getSelectedRow());
            System.out.println(armamentoTable.getSelectedRow() + "" + selectedArma.getNumSerie());
            fa.actualizarArmamento(selectedArma.getNumSerie(), nuevoArma);
        }

        m.setFilas(fa.obtenerArmamento(aSerieBuscarText.getText(), aModeloBuscarText.getText(), aTipoBuscarText.getText()));

    }//GEN-LAST:event_aGuardarButtonActionPerformed

    private void aBorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBorrarButtonActionPerformed

        ModeloTablaArmamento m;
        m = (ModeloTablaArmamento)armamentoTable.getModel();

        Armamento selectedArma = m.obtenerArma(armamentoTable.getSelectedRow());

        fa.borrarArmamento(selectedArma.getNumSerie());

        m.setFilas(fa.obtenerArmamento(aSerieBuscarText.getText(), aModeloBuscarText.getText(), aTipoBuscarText.getText()));

    }//GEN-LAST:event_aBorrarButtonActionPerformed

    private void aUbicacionIntTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aUbicacionIntTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aUbicacionIntTextActionPerformed

    private void aBuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBuscarButtonActionPerformed
        buscarArmamento();
    }//GEN-LAST:event_aBuscarButtonActionPerformed

    private void resumenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumenTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resumenTableMouseClicked

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        actualizarResumen();
    }//GEN-LAST:event_actualizarButtonActionPerformed

    public void buscarArmamento(){
        ModeloTablaArmamento m;
    
        m=(ModeloTablaArmamento) armamentoTable.getModel();
        m.setFilas(fa.obtenerArmamento(aSerieBuscarText.getText(), aModeloBuscarText.getText(), aTipoBuscarText.getText()));
        //Funcion Principal -> FachApp -> GestionUsuarios -> FachBD ->  DAO Usuarios
        
        if (m.getRowCount() > 0) {
            armamentoTable.setRowSelectionInterval(0, 0); //Cojemos la primera fila de la tabla
            aSerieIntText.setText( String.valueOf(m.obtenerArma(armamentoTable.getSelectedRow()).getNumSerie()) );
            aModeloIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getModelo());
            aTipoIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getTipo());
            aEstadoIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getEstado());
            aUbicacionIntText.setText(m.obtenerArma(armamentoTable.getSelectedRow()).getUbicacion());
            aFechaIntText.setText( String.valueOf(m.obtenerArma(armamentoTable.getSelectedRow()).getFechaAdquisicion()) );

            aGuardarButton.setEnabled(true);
            aBorrarButton.setEnabled(true);
        }
        else{
            aGuardarButton.setEnabled(false);
            aBorrarButton.setEnabled(false);
        }
    }
    
    public void buscarEquipo(){
        ModeloTablaEquipo m;
    
        m=(ModeloTablaEquipo) equipoTable.getModel();
        m.setFilas(fa.obtenerEquipo(eIdBuscarText.getText(), eNombreBuscarText.getText(), modoEquipo));
        //Funcion Principal -> FachApp -> GestionUsuarios -> FachBD ->  DAO Usuarios
        
        if (m.getRowCount() > 0) {
            equipoTable.setRowSelectionInterval(0, 0); //Cojemos la primera fila de la tabla
            eNombreIntText.setText(m.obtenerEquipo(equipoTable.getSelectedRow()).getNombre());
            eTipoIntText.setText(m.obtenerEquipo(equipoTable.getSelectedRow()).getTipo());
            eCompanhiaIntText.setText(m.obtenerEquipo(equipoTable.getSelectedRow()).getCompanhia());
            eIdIntText.setText(String.valueOf(m.obtenerEquipo(equipoTable.getSelectedRow()).getId()));
            eModoIntText.setText(m.obtenerEquipo(equipoTable.getSelectedRow()).getPropiedad());
            eFechaIntText.setText( String.valueOf(m.obtenerEquipo(equipoTable.getSelectedRow()).getFechaAdquisicion()) );

            eGuardarButton.setEnabled(true);
            eBorrarButton.setEnabled(true);
        }
        else{
            eGuardarButton.setEnabled(false);
            eBorrarButton.setEnabled(false);
        }
    }
    
    public void actualizarResumen(){
        ModeloTablaArmamentoResumen m;
        m = (ModeloTablaArmamentoResumen)resumenTable.getModel();
        
        HashMap<String, Integer> resu;
        resu = fa.obtenerResumen();
        m.setFilas(resu);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aBorrarButton;
    private javax.swing.JButton aBuscarButton;
    private javax.swing.JLabel aEstadoIntLabel;
    private javax.swing.JTextField aEstadoIntText;
    private javax.swing.JLabel aFechaIntLabel;
    private javax.swing.JTextField aFechaIntText;
    private javax.swing.JButton aGuardarButton;
    private javax.swing.JLabel aModeloBuscarLabel;
    private javax.swing.JTextField aModeloBuscarText;
    private javax.swing.JLabel aModeloIntLabel;
    private javax.swing.JTextField aModeloIntText;
    private javax.swing.JLabel aNuevoAvisoLabel;
    private javax.swing.JButton aNuevoButton;
    private javax.swing.JButton aSalirButton;
    private javax.swing.JLabel aSerieBuscarLabel;
    private javax.swing.JTextField aSerieBuscarText;
    private javax.swing.JLabel aSerieIntLabel;
    private javax.swing.JTextField aSerieIntText;
    private javax.swing.JLabel aTipoBuscarLabel;
    private javax.swing.JTextField aTipoBuscarText;
    private javax.swing.JLabel aTipoIntLabel;
    private javax.swing.JTextField aTipoIntText;
    private javax.swing.JScrollPane aTuplasPane;
    private javax.swing.JLabel aUbicacionIntLabel;
    private javax.swing.JTextField aUbicacionIntText;
    private javax.swing.JButton actualizarButton;
    private javax.swing.JPanel armamentoPane;
    private javax.swing.JTabbedPane armamentoTabbedPane;
    private javax.swing.JTable armamentoTable;
    private javax.swing.JButton eBorrarButton;
    private javax.swing.JButton eBuscarButton;
    private javax.swing.JLabel eCompanhiaIntLabel;
    private javax.swing.JTextField eCompanhiaIntText;
    private javax.swing.JLabel eFechaIntLabel;
    private javax.swing.JTextField eFechaIntText;
    private javax.swing.JButton eGuardarButton;
    private javax.swing.JLabel eIdBuscarLabel;
    private javax.swing.JTextField eIdBuscarText;
    private javax.swing.JLabel eIdIntLabel;
    private javax.swing.JTextField eIdIntText;
    private javax.swing.JComboBox<String> eModoComboBox;
    private javax.swing.JLabel eModoIntLabel;
    private javax.swing.JTextField eModoIntText;
    private javax.swing.JLabel eNombreBuscarLabel;
    private javax.swing.JTextField eNombreBuscarText;
    private javax.swing.JLabel eNombreIntLabel;
    private javax.swing.JTextField eNombreIntText;
    private javax.swing.JLabel eNuevoAvisoLabel;
    private javax.swing.JButton eNuevoButton;
    private javax.swing.JButton eSalirButton;
    private javax.swing.JLabel eTipoIntLabel;
    private javax.swing.JTextField eTipoIntText;
    private javax.swing.JScrollPane eTuplasPane;
    private javax.swing.JPanel equipoPane;
    private javax.swing.JTable equipoTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane resumenPane;
    private javax.swing.JTable resumenTable;
    // End of variables declaration//GEN-END:variables
}
