/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.FachadaAplicacion;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import aplicacion.Cuartel;
import aplicacion.Miembro;
/**
 *
 * @author alumnogreibd
 */
public class VMiembroAcceder extends javax.swing.JDialog {
    
    aplicacion.FachadaAplicacion fa;
    Miembro miembro;
    
    
    /**
     * Creates new form VCuartelMenu
     */
    public VMiembroAcceder(java.awt.Frame parent, boolean modal, FachadaAplicacion fa, Miembro miembro) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        this.miembro = miembro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        buscarNombre = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCuartelMenu = new javax.swing.JTable();
        BotonAsignar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de cuarteles");

        label1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        label1.setText("Nombre:");

        buscarNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        BotonBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        TablaCuartelMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TablaCuartelMenu.setModel(new ModeloTablaCuartelAcceder());
        TablaCuartelMenu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaCuartelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCuartelMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCuartelMenu);

        BotonAsignar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonAsignar.setText("Asignar");
        BotonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAsignarActionPerformed(evt);
            }
        });

        BotonSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(BotonBuscar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(BotonSalir)
                            .addGap(291, 291, 291)
                            .addComponent(BotonAsignar))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonBuscar)
                            .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonSalir)
                            .addComponent(BotonAsignar))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        buscarCuarteles();
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TablaCuartelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCuartelMenuMouseClicked
        // TODO add your handling code here:
        
        ModeloTablaCuartelAcceder m = (ModeloTablaCuartelAcceder) TablaCuartelMenu.getModel();
        int fila = TablaCuartelMenu.getSelectedRow();
        
        if(fila != -1){
            Cuartel cuartel = m.obtenerCuarteles(TablaCuartelMenu.getSelectedRow());
            
            if(fa.existeMiembroCuartel(miembro.getDni(), cuartel.getNombre())){
                BotonAsignar.setText("Deasignar");
            }else{
                BotonAsignar.setText("Asignar");
            }
        }
    }//GEN-LAST:event_TablaCuartelMenuMouseClicked

    private void BotonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAsignarActionPerformed

        ModeloTablaCuartelAcceder m = (ModeloTablaCuartelAcceder) TablaCuartelMenu.getModel();
        Cuartel cuartel = m.obtenerCuarteles(TablaCuartelMenu.getSelectedRow());
        if(fa.existeMiembroCuartel(miembro.getDni(), cuartel.getNombre())){
            fa.borrarAsignacion(miembro.getDni(), cuartel.getNombre());
            BotonAsignar.setText("Asignar");
        }else{
            fa.asignarMiembroCuartel(miembro,cuartel);
            BotonAsignar.setText("Deasginar");
        }
        
    }//GEN-LAST:event_BotonAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAsignar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTable TablaCuartelMenu;
    private javax.swing.JTextField buscarNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

    public void buscarCuarteles(){
        ModeloTablaCuartelAcceder m;
        
        int idGrupo = miembro.getIdGrupo();
        String nombreCuartel = buscarNombre.getText();
        
        m = (ModeloTablaCuartelAcceder) TablaCuartelMenu.getModel();
        m.setFilas(fa.obtenerCuarteles(nombreCuartel, idGrupo));
        
        if(m.getRowCount() > 0){
            TablaCuartelMenu.setRowSelectionInterval(0, 0);
        }
    }
}


